baseURL: "https://anawin-note-something.netlify.app/"
languageCode: "en-us"
title: "Anawin Note Something..."
theme: "ga-hugo-theme-master"

taxonomies:
  tag: tags
  category: categories
  mood: moods